In [7]:
import torch

#1. Tensor 
x = torch.empty(1) # scalar
print(f"empty(1):" , x)

x = torch.empty(3) # vector
print(f"empty(3):" , x) 

x = torch.empty(2,3) # matrix
print(f"empty(2,3):" , x)

x = torch.empty(2,2,3)
print(f"empty(2,2,3):" , x)

x = torch.rand(5,3) # ramdom number btw [0,1]
print("torch.rand(5,3):",x)

x = torch.ones(5,3) # fill 1
print("torch.ones(5,3):",x)

x = torch.zeros(5,3) # fill 0
print("torch.zeros(5,3):",x)

empty(1): tensor([4.8628e+33])
empty(3): tensor([3.5873e-43, 0.0000e+00, 5.0072e+33])
empty(2,3): tensor([[1.6853e+22, 5.3779e+22, 1.6411e-07],
        [8.4710e-07, 5.3642e-08, 2.1748e+23]])
empty(2,2,3): tensor([[[1.4013e-45, 0.0000e+00, 1.4013e-45],
         [0.0000e+00, 1.4013e-45, 0.0000e+00]],

        [[1.4013e-45, 0.0000e+00, 1.4013e-45],
         [0.0000e+00, 1.4013e-45, 0.0000e+00]]])
torch.rand(5,3): tensor([[0.4563, 0.2799, 0.9275],
        [0.4697, 0.1239, 0.1435],
        [0.9711, 0.9592, 0.5413],
        [0.6499, 0.2360, 0.1055],
        [0.7113, 0.3207, 0.1988]])
torch.ones(5,3): tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.zeros(5,3): tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [10]:
# check size
print("size:",x.size())
print("size(0)",x.size(0)) # access with argument

print("shape",x.shape)
print("shape[0]",x.shape[0]) # access with index

size: torch.Size([5, 3])
size(0) 5
shape torch.Size([5, 3])
shape[0] 5


In [14]:
# check data type
print(x.dtype)

# specify types, float32 default
x = torch.zeros(5,3, dtype=torch.float16)
print(x)

# check type
print(x.dtype)

torch.float16
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)
torch.float16


In [15]:
# construct from data
x = torch.tensor([5.5, 3])
print(x, x.dtype)

tensor([5.5000, 3.0000]) torch.float32


In [16]:
# require_grad argument
# This will tell pytorch that it will need to calculate the gradients for this tensor
# later in your optimization steps 
# i.e. this is a variable in your model that you want to optimize
# default = False
x = torch.tensor([5.5,3], requires_grad=True)
print(x)

tensor([5.5000, 3.0000], requires_grad=True)


In [20]:
# Operation
x = torch.ones(2,2)
y = torch.rand(2,2)

# elementwise addition
z = x + y
print(z)
print(torch.add(x,y)) #return tensor
print()
# in place addition, everything with a _ symbol = inplace operation
# i.e. it will modify the variable
# y.add_(x)

print(x)
print(y)
print(z)
print(y.add_(x))

tensor([[1.6447, 1.1669],
        [1.8677, 1.7070]])
tensor([[1.6447, 1.1669],
        [1.8677, 1.7070]])

tensor([[1., 1.],
        [1., 1.]])
tensor([[0.6447, 0.1669],
        [0.8677, 0.7070]])
tensor([[1.6447, 1.1669],
        [1.8677, 1.7070]])
tensor([[1.6447, 1.1669],
        [1.8677, 1.7070]])


In [21]:
# subtraction 
z = x - y
z = torch.sub(x,y)
print(z)

# multiplication
z = x * y
z = torch.mul(x,y)
print(z)

# division
z = x / y
z = torch.div(x,y)
print(z)

tensor([[-0.6447, -0.1669],
        [-0.8677, -0.7070]])
tensor([[1.6447, 1.1669],
        [1.8677, 1.7070]])
tensor([[0.6080, 0.8570],
        [0.5354, 0.5858]])


In [24]:
# slicing
x = torch.rand(5,3)
print(x)
print("x[:,0]", x[:,0]) # all rows, column 0
print("x[1,:]",x[1,:]) # rows 1, all column
print("x[1,1]",x[1,1]) # element at 1,1 -> return tensor

# Get the actual value if only 1 element in your tensor
print("x[1,1].item()",x[1,1].item()) # return actual value

tensor([[0.5547, 0.7607, 0.9350],
        [0.5759, 0.5815, 0.8015],
        [0.0365, 0.1241, 0.9106],
        [0.7509, 0.3969, 0.2407],
        [0.9198, 0.7302, 0.6738]])
x[:,0] tensor([0.5547, 0.5759, 0.0365, 0.7509, 0.9198])
x[1,:] tensor([0.5759, 0.5815, 0.8015])
x[1,1] tensor(0.5815)
x[1,1].item() 0.5814944505691528


In [26]:
# reshape with torch.view()
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8) # the size -1 -> pytorch will automatically determine the necessary size
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [30]:
# Numpy
# convert from tensor to numpy

a = torch.ones(5)
print(a)

b = a.numpy()
# a.add_(1)
print(b)
print(type(b))

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [31]:
# Careful: If the tensor is on the CPU (not the GPU)
# both objects will share the same memory location, so changing one 
# will also change the other
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [36]:
# convert from numpy to tensor
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a) # share the same memory
c = torch.tensor(a) # copy -> new variable

print(a)
print(b)
print(c)

a +=1
print()
# del a
print(a)
print(b)
print(c)



[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [42]:
# GPU Support

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# if you have more than 1 gpu -> device0 = ... "cuda:0" ; device1 = ... "cuda:1"
x = torch.rand(2,2).to(device) # move tensors to GPU device
#x = x.to("cpu")
#x = x.to("cuda")

x = torch.rand(2,2,device=device) # or directly create them on GPU

In [44]:
a = torch.ones(5,device=device)
print(a)

b = a.cpu().numpy() # copy value to cpu first and then convert to numpy -> doesn't share the same memory
a.add_(1)
print(b)
print(type(b))

tensor([1., 1., 1., 1., 1.], device='cuda:0')
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
